### ISSUE TITLE
Error in cwt function

### ISSUE THREAD

**Issue by mcardenass** [Priyanshurgupta/t-f-normalization#1]
I get the following error when calling the cwt function:

 Traceback (most recent call last):
   Celda In[20], línea 7
    amplitude, scale = cwt(test[0]. datos, dt=1, w0=6, fmin=fmin, fmax=fmax, nf=filters)
 ValueError: too many values to unpack (expected 2) 

 Apparently, the function only returns the amplitude vector but not the scale. Will it be the Obspy version?

Thank you in advance

**Comment by Priyanshurgupta** [comment]
You need to return scales also from the source code
obspy.signal.tf_misfit.cwt, it only returns amplitude in the source code.

**Comment by mcardenass** [comment]
Hi Priyan,

The line that indicates the error is from the original code. 

amplitude, scale = cwt(test[0].data, dt=1, w0=6, fmin=fmin, fmax=fmax, nf=filters)

I have adapted some lines to achieve the result. I observe that the record is normalized and the amplitude spectrum is practically flat in the useful frequency range. However, I still have doubts about the mistake.
......
#from obspy.signal.tf_misfit import cwt
from ssqueezepy import cwt
from pycwt import wavelet
....
#amplitude, scale = cwt(test[0].data, dt=1, w0=6, fmin=fmin, fmax=fmax, nf=filters)
amplitude, scale = cwt(test[0].data,'morlet')
amplitude_norm = amplitude/np.abs(amplitude)
test_norm=wavelet.icwt(amplitude_norm, scale, 1)

Regards

Martín

**Comment by Priyanshurgupta** [comment]
I observe that you are calling cwt from ssqueezepy, which actually takes different arguments for cwt function than that of cwt imported from obspy library. To call scales in the cwt function of obspy, you need to edit the cwt file of the source and return scales. 
Additionally, you can use cwt function from any library but please check their input arguments.

**Comment by mcardenass** [comment]
Thanks Priyan,

The wavelet normalization is fine, I will continue with the cross-correlations.
